SET FOREIGN_KEY_CHECKS = 0;
DROP VIEW IF EXISTS central_received_local_events;
DROP TABLE IF EXISTS schedule_sync_acknowledgements;
DROP TABLE IF EXISTS schedule_sync_outbox;
DROP TABLE IF EXISTS notification_outbox;
DROP TABLE IF EXISTS refund_records;
DROP TABLE IF EXISTS show_cancellations;
DROP TABLE IF EXISTS show_reschedules;
DROP TABLE IF EXISTS show_change_history;
DROP TABLE IF EXISTS central_sync_outbox;
DROP TABLE IF EXISTS central_sync_conflicts;
DROP TABLE IF EXISTS central_sync_inbox;
DROP TABLE IF EXISTS central_sync_api_request_log;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS central_payment_audit_logs;
DROP TABLE IF EXISTS central_confirmed_seats;
DROP TABLE IF EXISTS central_booking_items;
DROP TABLE IF EXISTS central_bookings;
DROP TABLE IF EXISTS central_seat_hold_items;
DROP TABLE IF EXISTS central_seat_holds;
DROP TABLE IF EXISTS show_authority_state;
DROP TABLE IF EXISTS booking_authority_policy;
DROP TABLE IF EXISTS show_pricing;
DROP TABLE IF EXISTS shows;
DROP TABLE IF EXISTS seat_layout_seats;
DROP TABLE IF EXISTS seat_layouts;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS screens;
DROP TABLE IF EXISTS theatres;
DROP TABLE IF EXISTS agent_clients;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS central_sessions;
DROP TABLE IF EXISTS central_users;
SET FOREIGN_KEY_CHECKS = 1;
SOURCE central-app/sql/central_schema.sql;
